# Generated by Django 3.2.18 on 2023-04-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'open hour',
                'verbose_name_plural': 'open hours',
            },
        ),
    ]
