# Generated by Django 3.2.18 on 2023-04-18 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0003_booking_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='table',
            name='opening_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
