# Generated by Django 3.2.18 on 2023-04-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0006_auto_20230419_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
