# Generated by Django 3.2.18 on 2023-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0008_customer_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
