# Generated by Django 3.2.18 on 2023-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.CharField(default=2, max_length=50),
        ),
    ]
