# Generated by Django 3.2.18 on 2023-04-23 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0003_auto_20230423_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='party_size',
            new_name='number_of_guests',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='table_number',
        ),
        migrations.RemoveField(
            model_name='table',
            name='available_times',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
