# Generated by Django 3.2.18 on 2023-04-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0004_auto_20230423_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
