# Generated by Django 3.2.18 on 2023-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0006_alter_booking_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(),
        ),
    ]
