# Generated by Django 3.2.18 on 2023-04-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0007_alter_booking_reservation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
    ]
