# Generated by Django 3.2.18 on 2023-04-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0010_auto_20230428_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_ends',
            field=models.TimeField(blank=True),
        ),
    ]
