# Generated by Django 3.2.18 on 2023-04-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0011_alter_booking_reservation_ends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='arrival',
            new_name='reservation_date_and_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_ends',
        ),
    ]
