# Generated by Django 3.2.18 on 2023-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0012_auto_20230428_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
