# Generated by Django 3.2.18 on 2023-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0013_alter_booking_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date_and_time',
            field=models.DateTimeField(),
        ),
    ]
