# Generated by Django 3.2.18 on 2023-04-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0014_alter_booking_reservation_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
