# Generated by Django 3.2.18 on 2023-04-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0018_booking_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
    ]
