# Generated by Django 3.2.18 on 2023-04-28 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0019_remove_booking_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reservation_date_and_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
