# Generated by Django 3.2.18 on 2023-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0021_alter_booking_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[('Pending', 'Pending'), ('Booked', 'Booked')], default='Pending'),
        ),
    ]
