# Generated by Django 3.2.18 on 2023-04-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0023_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
    ]
