# Generated by Django 3.2.18 on 2023-04-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutus_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
    ]
