# Generated by Django 3.2.18 on 2023-04-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20230424_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='thingsweoffer',
            options={'verbose_name_plural': 'things we offer'},
        ),
    ]
