# Generated by Django 3.2.18 on 2023-04-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'menu item', 'verbose_name_plural': 'menu items'},
        ),
    ]
